### ISSUE TITLE
Replace `editor` with `writer`

### ISSUE THREAD

**Issue by MathiasGmeiner** [HashandSalt/kirby-recurr#2]
If you use this plugin with Kirby 3.6 you get an error on the `edescription` field:

`Invalid field type ("editor")`

to be fully functionally with 3.6 the field type on line 36  in `site/plugins/kirby-recurr/blueprints/fields/event.yml` has to be replaced with `type: writer`

**Comment by HashandSalt** [comment]
Woahhh this has been hanging about a while! Fixed it.
